"""
Sport-specific configuration for CBB and NBA analysis modes.
"""

CBB_TEAM_ABBREV = {
    "st": "state",
    "penn st": "penn state",
    "michigan st": "michigan state",
    "ohio st": "ohio state",
    "iowa st": "iowa state",
    "kansas st": "kansas state",
    "utah st": "utah state",
    "colorado st": "colorado state",
    "san jose st": "san jose state",
    "fresno st": "fresno state",
    "boise st": "boise state",
    "oregon st": "oregon state",
    "arizona st": "arizona state",
    "washington st": "washington state",
    "florida st": "florida state",
    "nc st": "nc state",
    "n carolina st": "nc state",
    "north carolina st": "nc state",
    "usc": "usc",
    "ucf": "ucf",
    "vmi": "virginia military",
    "smu": "southern methodist",
    "tcu": "tcu",
    "lsu": "louisiana state",
    "ole miss": "ole miss",
    "unlv": "unlv",
    "utep": "utep",
    "utsa": "utsa",
    "uab": "uab",
    "fiu": "florida international",
    "fau": "florida atlantic",
    "niu": "northern illinois",
    "uic": "illinois chicago",
    "uconn": "connecticut",
    "brigham young": "byu",
}

NBA_TEAM_ABBREV = {
    # Abbreviated city/team names → full team name
    # (word-prefix matching handles "Golden State" → "Golden State Warriors" automatically;
    #  these handle cases where VSIN uses 2-3 letter codes or non-standard shortening)
    "gs": "golden state warriors",
    "gsw": "golden state warriors",
    "gs warriors": "golden state warriors",
    "okc": "oklahoma city thunder",
    "okc thunder": "oklahoma city thunder",
    "sa": "san antonio spurs",
    "sas": "san antonio spurs",
    "sa spurs": "san antonio spurs",
    "no": "new orleans pelicans",
    "nop": "new orleans pelicans",
    "no pelicans": "new orleans pelicans",
    "ny": "new york knicks",
    "nyk": "new york knicks",
    "ny knicks": "new york knicks",
    "la lakers": "los angeles lakers",
    "lal": "los angeles lakers",
    "la clippers": "los angeles clippers",
    "lac": "los angeles clippers",
    "phx": "phoenix suns",
    "pho": "phoenix suns",
    "pho suns": "phoenix suns",
    "phi": "philadelphia 76ers",
    "phi 76ers": "philadelphia 76ers",
    "76ers": "philadelphia 76ers",
    "philly": "philadelphia 76ers",
    "mem": "memphis grizzlies",
    "mem grizzlies": "memphis grizzlies",
    "mil": "milwaukee bucks",
    "mil bucks": "milwaukee bucks",
    "min": "minnesota timberwolves",
    "min timberwolves": "minnesota timberwolves",
    "por": "portland trail blazers",
    "por trail blazers": "portland trail blazers",
    "utah": "utah jazz",
    "uta": "utah jazz",
    "uta jazz": "utah jazz",
    "cha": "charlotte hornets",
    "cha hornets": "charlotte hornets",
    "was": "washington wizards",
    "wsh": "washington wizards",
    "was wizards": "washington wizards",
    "bkn": "brooklyn nets",
    "bk": "brooklyn nets",
    "bkn nets": "brooklyn nets",
    "tor": "toronto raptors",
    "tor raptors": "toronto raptors",
    "orl": "orlando magic",
    "orl magic": "orlando magic",
    "dal": "dallas mavericks",
    "dal mavericks": "dallas mavericks",
    "sac": "sacramento kings",
    "sac kings": "sacramento kings",
    # DK API abbreviated city names
    "det": "detroit pistons",
    "det pistons": "detroit pistons",
    "bos": "boston celtics",
    "bos celtics": "boston celtics",
    "atl": "atlanta hawks",
    "atl hawks": "atlanta hawks",
    "chi": "chicago bulls",
    "chi bulls": "chicago bulls",
    "cle": "cleveland cavaliers",
    "cle cavaliers": "cleveland cavaliers",
    "hou": "houston rockets",
    "hou rockets": "houston rockets",
    "ind": "indiana pacers",
    "ind pacers": "indiana pacers",
    "mia": "miami heat",
    "mia heat": "miami heat",
    "den": "denver nuggets",
    "den nuggets": "denver nuggets",
}

SPORT_CONFIGS = {
    "cbb": {
        # CBB VSIN: one base URL, then click DK (default) and Circa tabs
        "vsin_dk_url": "https://data.vsin.com/college-basketball/betting-splits/",
        "vsin_circa_url": None,  # reached via tab click on the same page
        "vsin_use_tabs": True,
        "oddstrader_spreads_url": "https://www.oddstrader.com/ncaa-college-basketball/",
        "oddstrader_totals_url": "https://www.oddstrader.com/ncaa-college-basketball/?eid&g=game&m=total",
        "team_abbrev": CBB_TEAM_ABBREV,
        "display_name": "CBB",
        "threshold": 25,
    },
    "nba": {
        # NBA VSIN: fetched via DK JSON API + Circa HTML (no Playwright needed)
        "vsin_dk_url": "https://data.vsin.com/betting-splits/?source=DK&sport=NBA",
        "vsin_circa_url": "https://data.vsin.com/betting-splits/?source=CIRCA&sport=NBA",
        "vsin_use_tabs": False,
        "oddstrader_spreads_url": "https://www.oddstrader.com/nba/",
        "oddstrader_totals_url": "https://www.oddstrader.com/nba/?eid&g=game&m=total",
        "team_abbrev": NBA_TEAM_ABBREV,
        "display_name": "NBA",
        "threshold": 20,
    },
}


def get_config(sport: str) -> dict:
    """Return the config dict for the given sport ('cbb' or 'nba')."""
    return SPORT_CONFIGS.get(sport.lower(), SPORT_CONFIGS["cbb"])
